version: '3.1'

services:
  api_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: API_DB
  api:
    build: ./
    command: ./docker-entrypoint.sh
    volumes:
      - ./:/api
    ports:
      - "80:80"
    depends_on:
      - api_db

