# Generated by Django 3.0.3 on 2020-03-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='value',
        ),
    ]
